// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvBWC23VKkZUBVKENonDMJnNk-UVSy0E',
    appId: '1:66103869666:web:b8301cd883590bf811debb',
    messagingSenderId: '66103869666',
    projectId: 'iti-connect-52440',
    authDomain: 'iti-connect-52440.firebaseapp.com',
    storageBucket: 'iti-connect-52440.firebasestorage.app',
    measurementId: 'G-SGWYC1FZ4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsIDGc10X1ayZnHQtb_QZK-eClWJnVkqY',
    appId: '1:66103869666:android:d64c99a9dd36f75211debb',
    messagingSenderId: '66103869666',
    projectId: 'iti-connect-52440',
    storageBucket: 'iti-connect-52440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1FT1wSA3GrgVS22kPYmxH3sWyC6IPIs',
    appId: '1:66103869666:ios:eb94d26f1edd9da311debb',
    messagingSenderId: '66103869666',
    projectId: 'iti-connect-52440',
    storageBucket: 'iti-connect-52440.firebasestorage.app',
    iosBundleId: 'com.example.itiConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1FT1wSA3GrgVS22kPYmxH3sWyC6IPIs',
    appId: '1:66103869666:ios:eb94d26f1edd9da311debb',
    messagingSenderId: '66103869666',
    projectId: 'iti-connect-52440',
    storageBucket: 'iti-connect-52440.firebasestorage.app',
    iosBundleId: 'com.example.itiConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVvBWC23VKkZUBVKENonDMJnNk-UVSy0E',
    appId: '1:66103869666:web:1172374d3f4d228b11debb',
    messagingSenderId: '66103869666',
    projectId: 'iti-connect-52440',
    authDomain: 'iti-connect-52440.firebaseapp.com',
    storageBucket: 'iti-connect-52440.firebasestorage.app',
    measurementId: 'G-XVJE257XFJ',
  );
}
